title: Olin Software Toolboxes

collections:
  exercises:
    output: true
    permalink: :path/
  toolboxes:
    output: true
    permalink: :path/

defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      type: toolboxes
    values:
      layout: toolbox

plugins:
  - github-pages

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - scripts
  - vendor
