title: Olin Software Toolboxes
short_title: Olin Toolboxes

yandex_key: 8979f63665e2b423

collections:
  exercises:
    output: true
    permalink: :path/
  toolboxes:
    output: true
    permalink: :path/

defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      type: toolboxes
    values:
      layout: toolbox

plugins:
  - github-pages

livereload: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - scripts
  - vendor
