title: Olin Software Toolboxes
short_title: Olin Toolboxes

yandex_key: 8979f63665e2b423
submission_form: https://goo.gl/forms/jqbX0onzzyL9JgHm1

collections:
  exercises:
    output: true
    permalink: :path/
  toolboxes:
    output: true
    permalink: :path/

defaults:
  - scope:
      path: ''
    values:
      layout: default
  - scope:
      type: toolboxes
    values:
      layout: toolbox

plugins:
  - github-pages
  - jekyll-mermaid

livereload: true

mermaid:
  src: 'assets/js/mermaid.min.js'

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - scripts
  - vendor
