#!/usr/bin/env bash

set -e # halt script on error

bundle exec jekyll build

bundle exec htmlproofer \
  --alt-ignore /images/HtL_Banner.svg \
  --assume-extension \
  --check-html \
  --empty-alt-ignore \
  --report-missing-names \
  --report-script-embeds \
  --url-ignore '/127.0.0.1/' \
  ./_site

# External links are ignored for the following reasons:
# - 127.0.0.1 is an example; it works when the student is following the setup instructions
